# Generated by Django 4.2.9 on 2024-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
